.catalog:
  name: "RegisterCenter"
  version: "v0.1"
  description: "RegisterCenter"
  questions:
    - variable: "reg_server"
      label: "Register center Address"
      description: "Register center Address"
      type: "string"
      required: true
