.catalog:
  name: "RegisterCenter"
  version: "v0.1"
  description: "RegisterCenter"
  questions:
    - variable: "exp_port"
      label: "Port"
      description: "Port"
      default: 8001
      type: "int"
      required: true
